mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^', include('posts.urls', namespace='posts')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^chat/', include('chatrooms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
    contact_us,
    BlogViewListApiView,
    BlogRetrieveApiView,
    )

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^contact/$', contact_us, name='contact_us'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    url(r'^api/posts/$', BlogViewListApiView.as_view(), name='posts_api'),
    url(r'^api/posts/(?P<pk>\d+)/$', BlogRetrieveApiView.as_view(), name='detail_api'),

]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    PostModel = instance.__class__
    try:
        new_id = PostModel.objects.order_by("id").last().id + 1
    except:
        PostModel.objects.last() == 0
        new_id = 1
    return "%s/%s" %(new_id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            width_field="width_field", 
            height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms


from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]


class ContactusForm(forms.Form):
    email = forms.EmailField()
    full_name = forms.CharField()
    message = forms.CharField()

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import SessionAuthentication
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .forms import PostForm, ContactusForm
from .models import Post
from .serializers import BlogSerializer
from .pagination import BlogPagination


class BlogViewListApiView(generics.ListAPIView):
    queryset = Post.objects.all()
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = BlogSerializer
    pagination_class = BlogPagination


class BlogRetrieveApiView(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # message success
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active() #.order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
                ).distinct()
    paginator = Paginator(queryset_list, 4) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "Posts",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Post updated')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form":form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")


def contact_us(request):
    form = ContactusForm(request.POST or None)
    if form.is_valid():
        form_email = form.cleaned_data.get("email")
        form_message = form.cleaned_data.get("message")
        form_full_name = form.cleaned_data.get("full_name")
        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email]
        contact_message = "%s/%s via %s"%(
                form_full_name,
                form_message,
                form_email)
        some_html_message = """
        <h1>hello</h1>
        """
        send_mail(subject,
                contact_message,
                from_email,
                to_email,
                html_message=some_html_message,
                fail_silently=True)
    context = {
        "form": form,
    }

    return render(request, 'contact_us.html', context )

templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<html>
<head>
<title>{% block head_title %}Blog Kerala{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel='stylesheet' href='{% static "css/static.css" %}' />
<link rel='stylesheet' href='{% static "css/style.css" %}' />
    {% include 'navbar.html' %}

</head>
<body background="{% static 'img/bgd.jpg' %}">
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% include "messages_display.html" %}
<div class='container'>
{% block content %}{% endblock%}
</div>
<footer> <hr/>
    <div class="text-center">
      <h3 class="text-center">Share <i class="fa fa-hand-o-down" aria-hidden="true"></i>
</h3>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"> <i class="fa fa-facebook-square fa-3x"></i></a>
            <a href="https://twitter.com/home?status={{ request.build_absolute_uri }}">
            <i class="fa fa-twitter-square fa-3x"></i></a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}">
            <i class="fa fa-linkedin-square fa-3x"></i></a>
            <a href="#"><i class="fa fa-instagram fa-3x"></i></a>
            <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}">
            <i class="fa fa-google-plus-square  fa-3x"></i></a>
            <a data-pin-do="buttonBookmark" href="//www.pinterest.com/pin/create/button/">
                <i class="fa fa-pinterest-square fa-3x"></i></a>
            <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}">
             <i class="fa fa-reddit-square  fa-3x"></i></a>
            <br/>
            <hr/>
</div>
</footer>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
</script>
</body>
</html>

templates/contact_us.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
<div class='col-sm-6 col-sm-offset-3'>
<h1>Contact us</h1>
</div>
</div>

<div class="row">
<div class='col-sm-6 col-sm-offset-3'>


<form method='POST' action=''>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-primary' value='Send' />
</form>

</div>
</div>

{% endblock content %}

templates/messages_display.html
{% if messages %}

    <div class='container'>

     <div class="alert alert-info text-center" role="alert">
    {% for message in messages %}
    <h4>{{ message }}</h4>
    {% endfor %}
    </div>
    </div>


{% endif %}

templates/navbar.html
{% block navbar %}

<!-- Static navbar -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--<a class="navbar-brand" href="{% url 'posts:list' %}">Kerala Blog</a>-->
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'posts:list' %}">Home</a></li>
          <li><a href="{% url 'posts:contact_us' %}">Contact Us</a></li>
            <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" name="q" placeholder="Search Posts" value="{{ request.GET.q }}"/>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
         <ul class="nav navbar-nav navbar-right pull-right">
                <li><a href="{% url 'posts:posts_api' %}">Rest Api View</a> </li>
         {% if request.user.is_authenticated %}
               <li><a href="{% url 'auth_logout' %}">Logout</a> </li>
               {% else %}
               <li><a href="{% url 'registration_register' %}">Register</a> </li>
         {% endif %}
          </ul>

       {% if not request.user.is_authenticated %}


        <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Username"/>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Password "/>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
              </ul>
       {% endif %}

      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>


{% endblock %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    {% if instance.image %}
    <img src='{{ instance.image.url }}' class='img-responsive' />
    {% endif %}
<h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft</span> {% endif %}{{ instance.publish }}</small></h1>
{% if instance.user.get_full_name %}
<p>Author: {{ instance.user.get_full_name }}</p>
{% endif %}

<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<hr/>
</p>


<div class='row'>
<div class='col-sm-12'>

{{ instance.content|linebreaks }}

<hr/>
<br/>
<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>

</div>
</div>
</div>


{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Form</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>


{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
         <img src='{{ obj.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}
{% if user.is_authenticated %}
    <div class='col-sm-6 col-sm-offset-10'>
         <a href="{% url 'posts:create' %}">Create New</a>
    </div>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}